import "../styles/globals.css";
import "tailwindcss/tailwind.css";
import "react-calendar/dist/Calendar.css";

import type { AppProps } from "next/app";
import ApolloProvider from "../providers/ApolloProvider";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Loading from "../components/Loading/Loading";

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const [pageLoading, setPageLoading] = useState<boolean>(false);
  useEffect(() => {
    const handleStart = () => {
      setPageLoading(true);
    };
    const handleComplete = () => {
      setPageLoading(false);
    };

    router.events.on("routeChangeStart", handleStart);
    router.events.on("routeChangeComplete", handleComplete);
    router.events.on("routeChangeError", handleComplete);
  }, [router]);
  return (
    <>
      <Head>
        <title>Ericson Orias Funtanar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {pageLoading ? (
        <Loading />
      ) : (
        <ApolloProvider>
          <Component {...pageProps} />
        </ApolloProvider>
      )}
    </>
  );
}
export default MyApp;
